#!/bin/bash

# User Directory
dir=$(pwd)

# Distro
distro=$(source /etc/os-release; echo $NAME)

# Current Kernel in use
kernel=$(uname -r)

# Hostname
hostname=$(< /etc/hostname)

# Shell
shell=$(basename $SHELL)

# Current Uptime
uptime=$(uptime -p)

# Package Count (Gentoo)
packages=$(ls -d /var/db/pkg/*/* | wc -l)

# CPU
cpu=$(lscpu | sed -nr '/Model name/ s/.*:\s*(.*) @ .*/\1/p')

# Disk usage
disk=$(df -h --output=used,size / | awk 'NR == 2 { print $1" / "$2 }')

# Installation Date
birth=$(stat / | awk '/Birth: /{print $2}')

#########################################################################

# Display Fetch
echo -e "  $dir"
echo -e "       ├── Operating Distro"
echo -e "       │   └── $distro"
echo -e "       ├── Portage Packages"
echo -e "       │   └── $packages"
echo -e "       ├── Kernel"
echo -e "       │   └── $kernel"
echo -e "       ├── CPU"
echo -e "       │   └── $cpu"
echo -e "       ├── Shell"
echo -e "       │   └── $shell"
echo -e "       ├── Uptime"
echo -e "       │   └── $uptime"
echo -e "       └── Installation Date"
echo -e "           └── $birth"





